version: '3.8'
services:
  smb:
    build: ./smb-docker
    volumes:
      - ${SHARE}:/data
      - ${TOOLKIT}:/tools
      - ./smb-docker/etc/samba:/etc/samba
    network_mode: "host"

  dhcp:
    image: networkboot/dhcpd
    volumes:
      - ./dhcpd-docker/data:/data
    command: ${IFACE}
    network_mode: host

  observer:
    build: ./observer-docker
    volumes:
      - ${WATCHDIR}:/watchdir
      - ${WORKDIR}:/workdir #${WORKDIR}:/workdir
    environment:
      - hash=${HASH}
    network_mode: host
