version: '3.3'
services:
  smb:
    build: ./smb-docker
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ${SHARE}:/data
  dhcp:
    image: networkboot/dhcpd
    network_mode: "host"
    volumes:
      - ./dhcpd-docker/data:/data
    command: ${IFACE}

  observer:
    build: ./observer-docker
    volumes:
      - ${WATCHDIR}:/watchdir
      - ${WORKDIR}:/workdir #${WORKDIR}:/workdir
    environment:
      - hash=${HASH}
