* dfir-smb-share
A Docker-based SMB Share for DFIR work. Attention: WIP!

** Description
This repo provides a dockerized SMB-Share, which hashes incoming files automatically and timestamps them securely by utilizing a TSA.
For this purpose, three services - DHCPD, SMBD and a service for monitoring the file system - were orchestrated, which, when used together, enable the quick and isolated release of a folder of the examination system as an SMB share with a minimal footprint. In order not to have to carry out any configuration, a DHCP server is started on the specified network interface of the examination system, the actual SMB daemon provides a folder in which the toolkit is then to be copied. In the third Docker container is a Monitoring implemented on the basis of inotifywait, which monitors changes to files and their metadata. This monitors the folder shared as a network drive using inotifywait and creates a SHA-256 checksum immediately after the creation of a new file has been completed. In this way, the integrity of all artifacts collected from the examination object is automatically ensured. In order to bind the time to the artifact in addition to the integrity, a time stamping according to RFC-3161 is carried out, as suggested by Bruce Nikkel in 2016. With the help of openssl and curl, a from a previously generated hash in the form of a timestamping request is transmitted to the timestamping authority (TSA), which concatenates the current time stamp with the transmitted hash, hashes the result and with the private key of the TSA signed.1} This proves that the analysis result existed in the unchanged form at that time.

Thus, the simple command docker-compose up can start the DFIR-SMB share, after which the integrity for all newly created files is automatically documented in the specified directory and made available as a network drive and the respective file is given a cryptographic time stamp. Using inotifywait, a copy is also created in a directory to be specified on the examination system for immediate further examination, which takes place on a duplicate.
